server:
  port: 8189
  servlet:
    context-path: /market
spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/market?serverTimezone=Europe/Moscow&amp&useSSL=false
      username: root
      password: gtr120519
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
jwt:
  secret: tg5g98h45g98h45g9845hg98hf9834hf9834hjheriheriuher9g8h384y5934yhhtertg
